### ISSUE TITLE
No module named werkzeug.contrib error

### ISSUE THREAD

**Issue by JiyooonPark** [wikibook/flask#6]
I am having some problems with the library version or dependency in chapter 5. 
I am working with python 3.8, werkzeug version 2.0.1 
This is the error I get. 
`2021-08-10 11:15:00,684 - INFO - static folder : /home/jypark/Documents/GitHub/WebDevelopment/flask-repo/wikibooks/ch05/photolog/photolog/../static
2021-08-10 11:15:00,684 - INFO - template folder : ../templates
Traceback (most recent call last):
  File "/home/jypark/Documents/GitHub/WebDevelopment/flask-repo/wikibooks/ch05/photolog/runserver.py", line 14, in <module>
    application = create_app()    
  File "/home/jypark/Documents/GitHub/WebDevelopment/flask-repo/wikibooks/ch05/photolog/photolog/__init__.py", line 81, in create_app
    from photolog.cache_session import SimpleCacheSessionInterface
  File "/home/jypark/Documents/GitHub/WebDevelopment/flask-repo/wikibooks/ch05/photolog/photolog/cache_session.py", line 17, in <module>
    from werkzeug.contrib.cache import NullCache, SimpleCache, RedisCache
ModuleNotFoundError: No module named 'werkzeug.contrib'

Process finished with exit code 1'

I tried to downgrade the werkzeug version to 1.0.0 with pip install werkzeug==1.0.0
but then I get this error 
`Traceback (most recent call last):
  File "/home/jypark/Documents/GitHub/WebDevelopment/flask-repo/wikibooks/ch05/photolog/runserver.py", line 12, in <module>
    from photolog import create_app
  File "/home/jypark/Documents/GitHub/WebDevelopment/flask-repo/wikibooks/ch05/photolog/photolog/__init__.py", line 15, in <module>
    from flask import Flask, render_template, request, url_for
  File "/home/jypark/virenv/flask-env/lib/python3.8/site-packages/flask/__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "/home/jypark/virenv/flask-env/lib/python3.8/site-packages/flask/app.py", line 19, in <module>
    from werkzeug.local import ContextVar
ImportError: cannot import name 'ContextVar' from 'werkzeug.local' (/home/jypark/virenv/flask-env/lib/python3.8/site-packages/werkzeug/local.py)

Process finished with exit code 1`
Did anyone else have the same problem?
Thanks in advance!

**Comment by keatonh** [comment]
Hi,

I have updated the requirements.txt to be able to run runserver.py in ch05 accordance with the source code.
When the source code were uploaded, the version of Flask was 0.10 or something, which means that the total source code might not be able to run on the latest packages used in the sample codes.
Sorry for the inconvenience and please use the updated requirements.txt in order no to face the same errors.
Also do not forget use python3 branch if you use python3.

installing packages: pip install -r requirements.txt
uninstalling packages: pip uninstall -r requirements.txt

Thanks,
Keaton
